# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-19 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vpn_Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('hostname', models.CharField(max_length=50, verbose_name='\u4e3b\u673a\u540d')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('port', models.IntegerField(verbose_name='Port')),
                ('uid', models.CharField(max_length=32, verbose_name='\u7528\u6237\u540d')),
                ('passwd', models.CharField(max_length=50, null=True, verbose_name='\u5bc6\u7801')),
                ('ssh_key', models.BooleanField(default=True, verbose_name='\u542f\u7528SSHKey')),
                ('online', models.BooleanField(default=False, verbose_name='\u5728\u7ebf')),
            ],
            options={
                'verbose_name': 'vpn\u8282\u70b9',
                'verbose_name_plural': 'vpn\u8282\u70b9',
            },
        ),
        migrations.CreateModel(
            name='Vpn_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u7528\u6237\u540d')),
                ('passwd', models.CharField(max_length=50, verbose_name='\u5bc6\u7801')),
                ('online', models.BooleanField(default=False, verbose_name='\u5728\u7ebf')),
                ('start_time', models.DateTimeField(auto_now=True, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.DateTimeField(auto_now=True, verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('enable_lease', models.BooleanField(default=True, verbose_name='\u542f\u7528\u79df\u671f')),
            ],
            options={
                'verbose_name': 'vpn\u7528\u6237',
                'verbose_name_plural': 'vpn\u7528\u6237',
            },
        ),
    ]
