# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-19 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpn_user',
            name='node_list',
            field=models.ManyToManyField(default='', to='vpn.Vpn_Node', verbose_name='VPNServer'),
        ),
    ]
