# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-19 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0003_auto_20180619_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vpn_user',
            old_name='node_list',
            new_name='nodelist',
        ),
    ]
