# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-19 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0004_auto_20180619_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vpn_user',
            old_name='online',
            new_name='enable',
        ),
    ]
