# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-11 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0006_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpn_user',
            name='email',
            field=models.EmailField(default=2, max_length=254, verbose_name='\u90ae\u7bb1'),
            preserve_default=False,
        ),
    ]
