# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-13 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0007_vpn_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='\u7c7b\u578b')),
                ('bill_user', models.CharField(max_length=50, verbose_name='\u64cd\u4f5c\u4eba')),
                ('action', models.CharField(max_length=30, verbose_name='\u52a8\u4f5c')),
                ('time', models.DateTimeField(verbose_name='\u65f6\u95f4')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
            ],
            options={
                'verbose_name': '\u65e5\u5fd7',
                'verbose_name_plural': '\u65e5\u5fd7',
            },
        ),
    ]
