# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-13 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0008_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='bill_user',
            new_name='username',
        ),
        migrations.AddField(
            model_name='log',
            name='result',
            field=models.BooleanField(default=False, verbose_name='\u542f\u7528'),
        ),
    ]
