# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-13 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0009_auto_20180713_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='result',
            new_name='status',
        ),
    ]
