# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-16 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0011_auto_20180714_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpn_node',
            name='wanip',
            field=models.GenericIPAddressField(default='0.0.0.0', verbose_name='\u5916\u7f51IP'),
        ),
    ]
