# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-16 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0012_vpn_node_wanip'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='node',
            field=models.CharField(default='', max_length=50, verbose_name='\u8282\u70b9'),
        ),
    ]
