# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-17 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0013_log_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50, null=True, verbose_name='\u90ae\u7bb1'),
        ),
    ]
