# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-22 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0014_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpn_user',
            name='end_time',
            field=models.DateTimeField(verbose_name='\u7ed3\u675f\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='vpn_user',
            name='start_time',
            field=models.DateTimeField(verbose_name='\u5f00\u59cb\u65f6\u95f4'),
        ),
    ]
